In [1]:
import pandas as pd

In [2]:
train = pd.read_csv("C:/Users/nakul/Desktop/Fake_News_Detector/datasets/liar_dataset/train.csv")

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10269 entries, 0 to 10268
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    10269 non-null  int64
 1   label                 10269 non-null  object
 2   statement             10269 non-null  object
 3   subject               10269 non-null  object
 4   speaker               10269 non-null  object
 5   speaker_job_title     7367 non-null   object
 6   state_info            8058 non-null   object
 7   party_affiliation     10269 non-null  object
 8   barely_true_counts    10269 non-null  int64
 9   false_counts          10269 non-null  int64
 10  half_true_counts      10269 non-null  int64
 11  mostly_true_counts    10269 non-null  int64
 12  pants_on_fire_counts  10269 non-null  int64
 13  context               10169 non-null  object
dtypes: int64(6), object(8)
memory usage: 1.1+ MB

In [4]:
train.describe()

,id,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts
count,10269.000000,10269.000000,10269.000000,10269.000000,10269.000000,10269.000000
mean,6775.308793,11.560132,13.313857,17.195637,16.490505,6.202746
std,3911.481391,19.006447,24.140583,35.948211,36.251253,16.117701
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3385.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,6796.000000,2.000000,2.000000,3.000000,3.000000,1.000000
75%,10180.000000,12.000000,15.000000,13.000000,11.000000,5.000000
max,13531.000000,70.000000,114.000000,160.000000,163.000000,105.000000

In [5]:
missing = train.isnull().sum()

missing_df = pd.DataFrame({
    "missing_count": missing,
    "missing_percentage": (missing / len(train)) * 100
})

missing_df.sort_values("missing_percentage", ascending=False)

                      missing_count  missing_percentage
speaker_job_title              2902           28.259811
state_info                     2211           21.530821
context                         100            0.973805
statement                         0            0.000000
label                             0            0.000000
id                                0            0.000000
speaker                           0            0.000000
subject                           0            0.000000
barely_true_counts                0            0.000000
party_affiliation                 0            0.000000
false_counts                      0            0.000000
half_true_counts                  0            0.000000
mostly_true_counts                0            0.000000
pants_on_fire_counts              0            0.000000

In [6]:
train[train["speaker_job_title"].isnull()].head(20)

,id,label,statement,subject,speaker,speaker_job_title,state_info,party_affiliation,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,context
3,1123,false,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7,19,3,5,44,a news release
4,9028,half-true,The economic turnaround started at the end of ...,"economy,jobs",charlie-crist,NaN,Florida,democrat,15,9,20,19,2,an interview on CNN
6,2342,barely-true,Jim Dunnam has not lived in the district he re...,candidates-biography,republican-party-texas,NaN,Texas,republican,3,1,1,3,1,a press release.
8,5602,half-true,"However, it took $19.5 million in Oregon Lotte...",jobs,oregon-lottery,NaN,NaN,organization,0,0,1,0,1,a website
13,8616,mostly-true,The economy bled $24 billion due to the govern...,"economy,federal-budget,health-care",doonesbury,NaN,NaN,none,0,0,2,4,0,a Doonesbury strip in the Sunday comics
17,3863,barely-true,"U.S. Rep. Ron Kind, D-Wis., and his fellow Dem...",federal-budget,national-republican-congressional-committee,NaN,NaN,republican,18,9,8,5,8,a news release
23,2673,half-true,"Says Scott Walker favors cutting up to 350,000...","health-care,message-machine",greater-wisconsin-political-fund,NaN,Wisconsin,none,3,3,3,1,1,a campaign TV ad
37,1038,true,The nuclear test conducted in our nation this ...,military,north-korea,NaN,NaN,none,0,0,0,0,0,a released statement
38,2940,pants-fire,"In the case of a catastrophic event, the Atlan...","health-care,pop-culture",walking-dead,NaN,NaN,none,0,0,0,0,1,the TV show's season finale
41,12027,half-true,Says Marco Rubio skipped 18 defense votes incl...,"military,voting-record",keep-promise-1-pac,NaN,NaN,republican,0,1,1,0,0,a TV ad
42,5210,pants-fire,Rep. David Cicilline is responsible for the fe...,"energy,stimulus",national-republican-congressional-committee,NaN,NaN,republican,18,9,8,5,8,a news release
46,7990,pants-fire,Obamacare will provide insurance to all non-U....,"health-care,immigration",chain-email,NaN,NaN,none,11,43,8,5,105,a long-running chain email
48,12848,pants-fire,It was under Barack Obama and Hillary Clinton ...,"iraq,military",katrina-pierson,NaN,NaN,republican,0,0,0,0,1,an interview on CNN.
49,13503,true,Hillary Clinton in 2005 co-sponsored legislati...,patriotism,blog-posting,NaN,NaN,none,7,19,3,5,44,Townhall.com
51,13210,barely-true,"Maggie Hassan raised tuition, making it the hi...",education,national-republican-senatorial-committee,NaN,NaN,republican,11,5,7,2,5,an ad
59,7548,mostly-true,"In 2008, only 54 percent of Latinos in Texas w...","elections,population",battleground-texas,NaN,Texas,democrat,0,0,0,1,0,"an adviser's interview on the ""Colbert Report."""
60,6000,false,Only 2 percent of public high schools in the c...,"education,health-care",michelle-obama,NaN,Illinois,democrat,0,2,1,4,0,an interview with NPR
63,1833,mostly-true,"There are 321,092 public school teachers in Te...","education,message-machine,taxes",empower-texans,NaN,Texas,none,1,0,0,1,0,a Web video
68,6161,barely-true,U.S. Rep. Phil Gingrey gave the government the...,"criminal-justice,terrorism",michael-opitz,NaN,Georgia,republican,1,0,0,0,0,a YouTube ad
77,3005,barely-true,Says one out of three U.S. homeless men is a v...,"poverty,veterans",texas-veterans-commission,NaN,NaN,none,1,0,0,0,0,a newspaper article.

In [7]:
train[train["state_info"].isnull()].head(20)

,id,label,statement,subject,speaker,speaker_job_title,state_info,party_affiliation,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,context
3,1123,false,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7,19,3,5,44,a news release
8,5602,half-true,"However, it took $19.5 million in Oregon Lotte...",jobs,oregon-lottery,NaN,NaN,organization,0,0,1,0,1,a website
13,8616,mostly-true,The economy bled $24 billion due to the govern...,"economy,federal-budget,health-care",doonesbury,NaN,NaN,none,0,0,2,4,0,a Doonesbury strip in the Sunday comics
17,3863,barely-true,"U.S. Rep. Ron Kind, D-Wis., and his fellow Dem...",federal-budget,national-republican-congressional-committee,NaN,NaN,republican,18,9,8,5,8,a news release
21,9867,mostly-true,The United States has the highest corporate ta...,"corporations,taxes",eric-bolling,"Co-host on Fox News Channel's ""The Five""",NaN,none,2,1,1,1,0,"a discussion on Fox News' ""The Five"""
37,1038,true,The nuclear test conducted in our nation this ...,military,north-korea,NaN,NaN,none,0,0,0,0,0,a released statement
38,2940,pants-fire,"In the case of a catastrophic event, the Atlan...","health-care,pop-culture",walking-dead,NaN,NaN,none,0,0,0,0,1,the TV show's season finale
41,12027,half-true,Says Marco Rubio skipped 18 defense votes incl...,"military,voting-record",keep-promise-1-pac,NaN,NaN,republican,0,1,1,0,0,a TV ad
42,5210,pants-fire,Rep. David Cicilline is responsible for the fe...,"energy,stimulus",national-republican-congressional-committee,NaN,NaN,republican,18,9,8,5,8,a news release
43,7993,pants-fire,Says Ohio budget item later signed into law by...,"abortion,pundits,women",rachel-maddow,MSNBC host,NaN,none,6,6,4,6,1,"On “The Rachel Maddow Show,” broadcast on MSNBC"
46,7990,pants-fire,Obamacare will provide insurance to all non-U....,"health-care,immigration",chain-email,NaN,NaN,none,11,43,8,5,105,a long-running chain email
48,12848,pants-fire,It was under Barack Obama and Hillary Clinton ...,"iraq,military",katrina-pierson,NaN,NaN,republican,0,0,0,0,1,an interview on CNN.
49,13503,true,Hillary Clinton in 2005 co-sponsored legislati...,patriotism,blog-posting,NaN,NaN,none,7,19,3,5,44,Townhall.com
51,13210,barely-true,"Maggie Hassan raised tuition, making it the hi...",education,national-republican-senatorial-committee,NaN,NaN,republican,11,5,7,2,5,an ad
73,7425,mostly-true,The only time in our history when the debt has...,debt,david-cote,President and CEO of Honeywell International,NaN,none,0,0,0,1,0,a speech during a “Fix the Debt” press event
77,3005,barely-true,Says one out of three U.S. homeless men is a v...,"poverty,veterans",texas-veterans-commission,NaN,NaN,none,1,0,0,0,0,a newspaper article.
78,9165,false,Says Charlie Crist supports cuts to the Medica...,"health-care,medicare",republican-party-florida,NaN,NaN,republican,10,6,6,6,4,a Facebook post
82,3146,false,"In the past 20 years, Egypt has made great str...","foreign-policy,abc-news-week",sameh-shoukry,NaN,NaN,none,0,1,0,0,0,"an interview on ABC's ""This Week with Christia..."
99,7128,mostly-true,A foreclosure tax that would take effect in 20...,housing,national-association-realtors,NaN,NaN,none,0,0,0,1,0,a web post
100,5667,false,The Florida Department of Agricultures website...,guns,brady-campaign-prevent-gun-violence,NaN,NaN,none,1,1,0,0,0,a congressional briefing

In [8]:
train.loc[
    train["speaker_job_title"].isna(),
    "speaker"
].value_counts().head(20)

speaker
chain-email                                    142
charlie-crist                                   70
jeb-bush                                        63
blog-posting                                    59
sarah-palin                                     52
rick-santorum                                   46
national-republican-congressional-committee     46
nathan-deal                                     43
ron-johnson                                     37
republican-party-florida                        26
democratic-congressional-campaign-committee     26
democratic-national-committee                   25
ben-carson                                      25
republican-national-committee-republican        24
tommy-thompson                                  24
national-republican-senatorial-committee        24
bill-nelson                                     23
herman-cain                                     23
glenn-beck                                      21
state-democratic-party-wisconsin                20
Name: count, dtype: int64

In [9]:
train[train["speaker"] == "charlie-crist"][
    ["speaker", "speaker_job_title"]
].value_counts(dropna=False)

speaker        speaker_job_title
charlie-crist  NaN                  70
Name: count, dtype: int64

In [10]:
train[train["speaker"] == "jeb-bush"][
    ["speaker", "speaker_job_title"]
].value_counts(dropna=False)

speaker   speaker_job_title
jeb-bush  NaN                  63
Name: count, dtype: int64

In [11]:
train[train["speaker"] == "ron-johnson"][
    ["speaker", "speaker_job_title"]
].value_counts(dropna=False)

speaker      speaker_job_title
ron-johnson  NaN                  37
Name: count, dtype: int64

In [12]:
for speaker in ["charlie-crist", "jeb-bush", "sarah-palin"]:
    print("\n", speaker)

    print(
        train.loc[
            train["speaker"] == speaker,
            "speaker_job_title"
        ].value_counts(dropna=False)
    )

 charlie-crist
speaker_job_title
NaN    70
Name: count, dtype: int64

 jeb-bush
speaker_job_title
NaN    63
Name: count, dtype: int64

 sarah-palin
speaker_job_title
NaN    52
Name: count, dtype: int64

In [13]:
missing_summary = pd.DataFrame({
    "missing_count": train.isnull().sum(),
    "missing_percentage": train.isnull().mean() * 100
})

missing_summary.sort_values(
    "missing_percentage",
    ascending=False
)

                      missing_count  missing_percentage
speaker_job_title              2902           28.259811
state_info                     2211           21.530821
context                         100            0.973805
statement                         0            0.000000
label                             0            0.000000
id                                0            0.000000
speaker                           0            0.000000
subject                           0            0.000000
barely_true_counts                0            0.000000
party_affiliation                 0            0.000000
false_counts                      0            0.000000
half_true_counts                  0            0.000000
mostly_true_counts                0            0.000000
pants_on_fire_counts              0            0.000000

In [14]:
na_state = train.loc[train["state_info"].isna(), "speaker"]

In [16]:
train.loc[
    train["state_info"].isna(),
    "speaker"
].value_counts().head(20)

speaker
chain-email                                    142
facebook-posts                                  78
blog-posting                                    59
national-republican-congressional-committee     46
nathan-deal                                     43
rush-limbaugh                                   35
democratic-congressional-campaign-committee     26
republican-party-florida                        26
democratic-national-committee                   25
ben-carson                                      25
republican-national-committee-republican        24
national-republican-senatorial-committee        24
glenn-beck                                      21
rachel-maddow                                   20
viral-image                                     19
david-axelrod                                   18
club-growth                                     17
bill-oreilly                                    16
kasim-reed                                      16
sean-hannity                                    15
Name: count, dtype: int64

In [17]:
for speaker in [
    "nathan-deal",
    "ben-carson",
    "rush-limbaugh",
    "rachel-maddow"
]:
    print(f"\n{speaker}")

    print(
        train.loc[
            train["speaker"] == speaker,
            "state_info"
        ].value_counts(dropna=False)
    )

nathan-deal
state_info
NaN    43
Name: count, dtype: int64

ben-carson
state_info
NaN    25
Name: count, dtype: int64

rush-limbaugh
state_info
NaN    35
Name: count, dtype: int64

rachel-maddow
state_info
NaN    20
Name: count, dtype: int64

In [18]:
train.loc[train["speaker"].duplicated(), "speaker"].value_counts().head(20)

speaker
barack-obama       492
donald-trump       273
hillary-clinton    238
mitt-romney        179
scott-walker       149
john-mccain        147
chain-email        141
rick-perry         141
marco-rubio        116
rick-scott         114
ted-cruz            92
bernie-s            88
chris-christie      77
facebook-posts      77
charlie-crist       69
newt-gingrich       68
jeb-bush            62
joe-biden           62
blog-posting        58
paul-ryan           55
Name: count, dtype: int64

In [19]:
# Completely duplicated rows
train.duplicated().sum()

np.int64(0)

In [20]:
# Repeated statements
train["statement"].duplicated().sum()

np.int64(17)

In [21]:
train.loc[train["statement"].duplicated(), "statement"].value_counts().head(20)

statement
On changing the rules for filibusters on presidential nominees                                                                                                                                                                2
On abortion                                                                                                                                                                                                                   1
"Obama says Iran is a 'tiny' country, 'doesn't pose a serious threat.'"                                                                                                                                                       1
On support for gay marriage.                                                                                                                                                                                                  1
Four balanced budgets in a row, with no new taxes for anyone. The best job growth in 12 years. Nearly 130,000 new private-sector jobs. Merit pay to reward New Jerseys best teachers, and the most education funding ever.    1
On a cap-and-trade plan.                                                                                                                                                                                                      1
On the Trans-Pacific Partnership.                                                                                                                                                                                             1
On repealing the 17th Amendment                                                                                                                                                                                               1
During Sherrod Browns past decade as a D.C. politician, more than one out of every four jobs that has left America, left from Ohio. ... Sherrod Brown will own these horrendous Ohio job numbers next year.                   1
On torture.                                                                                                                                                                                                                   1
On support for the Export-Import Bank                                                                                                                                                                                         1
On the status of illegal immigrants                                                                                                                                                                                           1
Six justices on the U.S. Supreme Court have been confirmed in presidential election years since 1912.                                                                                                                         1
Says Mitt Romney flip-flopped on abortion.                                                                                                                                                                                    1
Twenty million Americans are out of work.                                                                                                                                                                                     1
Some 20,000 Delphi salaried retirees lost up to 70 percent of their pensions as a result of political favoritism and backroom deals.                                                                                          1
Name: count, dtype: int64

In [22]:
train["statement"].duplicated().sum()

np.int64(17)

In [23]:
train["statement"].value_counts().loc[lambda x: x > 1]

statement
On changing the rules for filibusters on presidential nominees                                                                                                                                                                3
Six justices on the U.S. Supreme Court have been confirmed in presidential election years since 1912.                                                                                                                         2
On abortion                                                                                                                                                                                                                   2
On repealing the 17th Amendment                                                                                                                                                                                               2
On torture.                                                                                                                                                                                                                   2
On a cap-and-trade plan.                                                                                                                                                                                                      2
During Sherrod Browns past decade as a D.C. politician, more than one out of every four jobs that has left America, left from Ohio. ... Sherrod Brown will own these horrendous Ohio job numbers next year.                   2
Four balanced budgets in a row, with no new taxes for anyone. The best job growth in 12 years. Nearly 130,000 new private-sector jobs. Merit pay to reward New Jerseys best teachers, and the most education funding ever.    2
"Obama says Iran is a 'tiny' country, 'doesn't pose a serious threat.'"                                                                                                                                                       2
On the Trans-Pacific Partnership.                                                                                                                                                                                             2
On support for the Export-Import Bank                                                                                                                                                                                         2
On support for gay marriage.                                                                                                                                                                                                  2
On the status of illegal immigrants                                                                                                                                                                                           2
Twenty million Americans are out of work.                                                                                                                                                                                     2
Says Mitt Romney flip-flopped on abortion.                                                                                                                                                                                    2
Some 20,000 Delphi salaried retirees lost up to 70 percent of their pensions as a result of political favoritism and backroom deals.                                                                                          2
Name: count, dtype: int64

In [24]:
duplicate_statements = train[
    train["statement"].duplicated(keep=False)
]

duplicate_statements.sort_values("statement")[
    ["id", "statement", "label", "speaker", "subject", "context"]
]

,id,statement,label,speaker,subject,context
848,828,"""Obama says Iran is a 'tiny' country, 'doesn't...",false,john-mccain,foreign-policy,a TV ad airing in Florida
1858,662,"""Obama says Iran is a 'tiny' country, 'doesn't...",false,john-mccain,foreign-policy,a TV ad
4852,4669,During Sherrod Browns past decade as a D.C. po...,half-true,josh-mandel,"economy,job-accomplishments,jobs",a news release
1594,4668,During Sherrod Browns past decade as a D.C. po...,half-true,josh-mandel,"economy,job-accomplishments,jobs",a news release
1538,7763,"Four balanced budgets in a row, with no new ta...",half-true,chris-christie,"education,state-budget,state-finances",a TV ad
2859,7756,"Four balanced budgets in a row, with no new ta...",mostly-true,chris-christie,"job-accomplishments,jobs,state-budget,state-fi...",a television ad
3269,1211,On a cap-and-trade plan.,false,tim-pawlenty,"cap-and-trade,climate-change,environment",a letter to the Minnesota delegation in Washin...
2885,2519,On a cap-and-trade plan.,false,scott-bruun,"cap-and-trade,climate-change,jobs",a candidate forum
709,5919,On abortion,false,mitt-romney,"abortion,corrections-and-updates",various statements
1014,8882,On abortion,half-true,charlie-crist,"abortion,candidates-biography",various statements
4953,8591,On changing the rules for filibusters on presi...,false,mitch-mcconnell,congressional-rules,speeches
9671,8589,On changing the rules for filibusters on presi...,false,barack-obama,congressional-rules,speeches
3666,8592,On changing the rules for filibusters on presi...,false,harry-reid,congressional-rules,speeches
2037,8918,On repealing the 17th Amendment,false,dan-patrick,"debates,elections,states",a debate
2710,8919,On repealing the 17th Amendment,false,david-dewhurst,"debates,elections,states",a debate
931,5914,On support for gay marriage.,true,mitt-romney,gays-and-lesbians,statements to the media.
1826,5894,On support for gay marriage.,false,barack-obama,"civil-rights,families,gays-and-lesbians,marriage",a TV interview
6805,11527,On support for the Export-Import Bank,false,glenn-grothman,trade,NaN
4222,11455,On support for the Export-Import Bank,false,ron-johnson,trade,On support for the Export-Import Bank
4399,12942,On the Trans-Pacific Partnership.,false,pat-toomey,trade,an op-ed in the Pittsburgh Post-Gazette.
2937,11404,On the Trans-Pacific Partnership.,false,hillary-clinton,trade,an interview on PBS Newshour
6987,10586,On the status of illegal immigrants,false,scott-walker,immigration,an interview
7269,10477,On the status of illegal immigrants,half-true,scott-walker,immigration,an interview
1071,630,On torture.,true,john-mccain,military,NaN
6780,995,On torture.,half-true,newt-gingrich,"human-rights,terrorism",a news interview
8428,4850,Says Mitt Romney flip-flopped on abortion.,true,democratic-national-committee,"abortion,message-machine-2012",a campaign ad
8935,4720,Says Mitt Romney flip-flopped on abortion.,true,jon-huntsman,"abortion,message-machine-2012",a web advertisement
1911,12079,Six justices on the U.S. Supreme Court have be...,true,mike-honda,"history,supreme-court",a column posted on Medium
7676,12073,Six justices on the U.S. Supreme Court have be...,true,gwen-moore,"congress,legal-issues,supreme-court",a tweet
8887,8311,"Some 20,000 Delphi salaried retirees lost up t...",half-true,michael-turner,"corporations,economy,financial-regulation,pens...",a news release
9779,5822,"Some 20,000 Delphi salaried retirees lost up t...",barely-true,michael-turner,"corporations,economy",a statement supporting Mitt Romney
7819,12032,Twenty million Americans are out of work.,half-true,john-kasich,"economy,jobs",a television ad
9429,12349,Twenty million Americans are out of work.,half-true,tom-marino,jobs,an interview on MSNBC.

In [25]:
label_counts = train.groupby("statement")["label"].nunique()

label_counts.value_counts()

label
1    10246
2        6
Name: count, dtype: int64

In [26]:
conflicting_statements = label_counts[label_counts > 1]

len(conflicting_statements)
conflicting_statements

statement
Four balanced budgets in a row, with no new taxes for anyone. The best job growth in 12 years. Nearly 130,000 new private-sector jobs. Merit pay to reward New Jerseys best teachers, and the most education funding ever.    2
On abortion                                                                                                                                                                                                                   2
On support for gay marriage.                                                                                                                                                                                                  2
On the status of illegal immigrants                                                                                                                                                                                           2
On torture.                                                                                                                                                                                                                   2
Some 20,000 Delphi salaried retirees lost up to 70 percent of their pensions as a result of political favoritism and backroom deals.                                                                                          2
Name: label, dtype: int64

In [27]:
train[
    train["statement"].isin(conflicting_statements.index)
].sort_values("statement")[
    ["statement", "label", "speaker", "context"]
]

,statement,label,speaker,context
1538,"Four balanced budgets in a row, with no new ta...",half-true,chris-christie,a TV ad
2859,"Four balanced budgets in a row, with no new ta...",mostly-true,chris-christie,a television ad
709,On abortion,false,mitt-romney,various statements
1014,On abortion,half-true,charlie-crist,various statements
931,On support for gay marriage.,true,mitt-romney,statements to the media.
1826,On support for gay marriage.,false,barack-obama,a TV interview
6987,On the status of illegal immigrants,false,scott-walker,an interview
7269,On the status of illegal immigrants,half-true,scott-walker,an interview
1071,On torture.,true,john-mccain,NaN
6780,On torture.,half-true,newt-gingrich,a news interview
8887,"Some 20,000 Delphi salaried retirees lost up t...",half-true,michael-turner,a news release
9779,"Some 20,000 Delphi salaried retirees lost up t...",barely-true,michael-turner,a statement supporting Mitt Romney

In [28]:
statement_label_counts = (
    train.groupby("statement")["label"]
         .nunique()
)

conflicting = statement_label_counts[
    statement_label_counts > 1
]

print("Conflicting statements:", len(conflicting))

Conflicting statements: 6

In [29]:
conflicting_rows = train[
    train["statement"].isin(conflicting.index)
]

print("Rows involved:", len(conflicting_rows))
percentage = len(conflicting_rows) / len(train) * 100

print(f"Percentage of training data: {percentage:.2f}%")

Rows involved: 12
Percentage of training data: 0.12%

# Labels

In [30]:
train["label"].value_counts()

label
half-true      2123
false          1998
mostly-true    1966
true           1683
barely-true    1657
pants-fire      842
Name: count, dtype: int64

In [31]:
train["label"].value_counts(normalize=True) * 100

label
half-true      20.673873
false          19.456617
mostly-true    19.145000
true           16.389132
barely-true    16.135943
pants-fire      8.199435
Name: proportion, dtype: float64

In [32]:
valid = pd.read_csv("C:/Users/nakul/Desktop/Fake_News_Detector/datasets/liar_dataset/valid.csv")
test = pd.read_csv("C:/Users/nakul/Desktop/Fake_News_Detector/datasets/liar_dataset/test.csv")

In [33]:
for name, df in [
    ("Train", train),
    ("Validation", valid),
    ("Test", test)
]:
    print(f"\n{name}")
    print(
        (df["label"].value_counts(normalize=True) * 100)
        .round(2)
    )

Train
label
half-true      20.67
false          19.46
mostly-true    19.14
true           16.39
barely-true    16.14
pants-fire      8.20
Name: proportion, dtype: float64

Validation
label
false          20.48
mostly-true    19.55
half-true      19.31
barely-true    18.46
true           13.16
pants-fire      9.03
Name: proportion, dtype: float64

Test
label
half-true      20.81
false          19.49
mostly-true    19.41
barely-true    16.68
true           16.45
pants-fire      7.17
Name: proportion, dtype: float64

In [34]:
for df in [train, valid, test]:
    df["label"] = df["label"].str.lower()

In [35]:
print(train["label"].unique())
print(valid["label"].unique())
print(test["label"].unique())

['false' 'half-true' 'mostly-true' 'true' 'barely-true' 'pants-fire']
['barely-true' 'pants-fire' 'false' 'half-true' 'true' 'mostly-true']
['true' 'false' 'half-true' 'pants-fire' 'barely-true' 'mostly-true']

# Statement

In [36]:
train["statement_char_length"] = train["statement"].str.len()

train["statement_word_count"] = (
    train["statement"]
    .str.split()
    .str.len()
)

In [37]:
train[
    ["statement_char_length", "statement_word_count"]
].describe()

       statement_char_length  statement_word_count
count           10269.000000          10269.000000
mean              106.323693             17.906515
std                45.101317              7.752818
min                11.000000              2.000000
25%                73.000000             12.000000
50%                99.000000             17.000000
75%               133.000000             22.000000
max               395.000000             66.000000

In [38]:
train.nlargest(10, "statement_word_count")[
    ["statement", "label", "speaker", "context", "statement_word_count"]
]

,statement,label,speaker,context,statement_word_count
4206,"""Let's pay attention to kids who are not going...",true,hillary-clinton,NaN,66
9991,Barbara Buono by the numbers: As a Trenton pol...,mostly-true,republican-governors-association,a gubernatorial campaign TV ad,65
427,Right now one of our highest job growth sector...,mostly-true,lou-greenwald,a press conference in Trenton,61
1275,"When Donald Trump spoke in Phoenix, he looked ...",half-true,tim-kaine,a vice presidential debate in Virginia,60
5039,"""He (Obama) has done several things well. Most...",false,mitt-romney,a 'Today Show' interview,60
4047,Mike Madigan made a fortune on tax appeals Sav...,barely-true,citizens-michael-mcauliffe-and-house-republica...,a video attack advertisement,57
6201,[When I was mayor] Providence was one of the f...,true,vincent-buddy-cianci,a TV debate,55
7430,"After Hurricane Katrina, Dallas and San Antoni...",false,chain-email,an e-mail,55
5375,This year President Obama canceled the 21st an...,barely-true,chain-email,a chain email,54
707,We spend more money on health care per capita ...,half-true,david-dewhurst,an editorial board meeting with the Austin Ame...,53

In [39]:
for limit in [30, 50, 100, 200]:
    count = (train["statement_word_count"] > limit).sum()

    print(
        f"> {limit} words: {count} "
        f"({count / len(train) * 100:.2f}%)"
    )

> 30 words: 744 (7.25%)
> 50 words: 15 (0.15%)
> 100 words: 0 (0.00%)
> 200 words: 0 (0.00%)

In [40]:
for limit in [3, 5, 10]:
    count = (train["statement_word_count"] <= limit).sum()

    print(
        f"<= {limit} words: {count} "
        f"({count / len(train) * 100:.2f}%)"
    )

<= 3 words: 27 (0.26%)
<= 5 words: 137 (1.33%)
<= 10 words: 1619 (15.77%)

In [41]:
train.nsmallest(20, "statement_word_count")[
    ["statement", "label", "speaker", "context", "statement_word_count"]
]

,statement,label,speaker,context,statement_word_count
709,On abortion,false,mitt-romney,various statements,2
1014,On abortion,half-true,charlie-crist,various statements,2
1071,On torture.,true,john-mccain,NaN,2
2953,On reconciliation,false,barack-obama,campaign speeches,2
6151,Were bankrupt.,false,gary-johnson,"a Republican presidential debate in Orlando, Fla.",2
6548,On abortion.,false,susan-combs,an interview,2
6780,On torture.,half-true,newt-gingrich,a news interview,2
7667,On sequestration,false,eric-cantor,a debate.,2
470,Crime is rising.,pants-fire,donald-trump,a speech after several primaries concluded,3
1027,On same-sex marriage.,false,hillary-clinton,a video with the Human Rights Campaign.,3
1178,NASCAR endorsed Trump,half-true,donald-trump,"a speech in Concord, N.C.",3
2215,The countrys bankrupt.,false,ron-paul,"in a debate in Ames, Iowa",3
2287,I was filibustered.,mostly-true,rob-portman,a news conference call,3
3494,On high-speed rail.,false,mike-haridopolos,a press statement.,3
3533,On abortion rights.,half-true,harold-ford-jr,comments on the subject over the past 10 years.,3
3636,Weve rebuilt China.,half-true,donald-trump,an interview with the New York Times,3
4304,On same-sex marriage,false,kasim-reed,NaN,3
4467,On transportation financing,half-true,chris-christie,an Assembly Budget Committee hearing,3
5811,On bipartisan redistricting.,false,thomas-norment-jr,a press release.,3
5959,On immigration reform,true,ed-gillespie,interviews,3

# punctuations, number etc in statements

In [42]:
train["has_number"] = train["statement"].str.contains(r"\d", regex=True)

train["has_number"].value_counts()

has_number
False    6245
True     4024
Name: count, dtype: int64

In [43]:
train.loc[
    train["has_number"],
    ["statement", "label"]
].head(10)

                                            statement        label
5   The Chicago Bears have had more starting quart...         true
8   However, it took $19.5 million in Oregon Lotte...    half-true
9   Says GOP primary opponents Glenn Grothman and ...  mostly-true
11  Since 2000, nearly 12 million Americans have s...    half-true
13  The economy bled $24 billion due to the govern...  mostly-true
15  In this last election in November, ... 63 perc...    half-true
18  Water rates in Manila, Philippines, were raise...    half-true
19  Almost 100,000 people left Puerto Rico last year.  mostly-true
23  Says Scott Walker favors cutting up to 350,000...    half-true
28  ISIS supporter tweeted at 10:34 a.m. Shooting ...        false

In [44]:
train["has_url"] = train["statement"].str.contains(
    r"http|www\.",
    case=False,
    regex=True
)

train["has_url"].value_counts()

has_url
False    10269
Name: count, dtype: int64

In [45]:
train["uppercase_count"] = train["statement"].apply(
    lambda x: sum(1 for c in x if c.isupper())
)

train["uppercase_count"].describe()

count    10269.000000
mean         3.608238
std          2.523496
min          0.000000
25%          2.000000
50%          3.000000
75%          5.000000
max         54.000000
Name: uppercase_count, dtype: float64

In [46]:
import string

train["punctuation_count"] = train["statement"].apply(
    lambda x: sum(1 for c in x if c in string.punctuation)
)

train["punctuation_count"].describe()

count    10269.000000
mean         2.873211
std          2.118907
min          0.000000
25%          1.000000
50%          2.000000
75%          4.000000
max         21.000000
Name: punctuation_count, dtype: float64

In [47]:
print("Shape:", train.shape)
print("Rows:", len(train))
print("Missing statements:", train["statement"].isna().sum())
print("Unique IDs:", train["id"].nunique())

Shape: (10269, 20)
Rows: 10269
Missing statements: 0
Unique IDs: 10269

In [48]:
pd.set_option("display.max_colwidth", None)
train.nlargest(10, "uppercase_count")[
    ["statement", "uppercase_count"]
]

,statement,uppercase_count
9092,"""Obama has proposed a 1.4% pay increase for active duty military in 2011. This is THE LOWEST SINCE 1973 ... A LOWER PAY INCREASE THAN WELFARE RECIPIENTS!!!""",54
5671,GEORGIA ROADWAY FATALITIES THIS YEAR: 59 PLEASE DRIVE SAFELY,49
5375,"This year President Obama canceled the 21st annual National Day of Prayer ceremony at the White House under the ruse of not wanting to offend anyone.BUT on September 25, 2009 from 4 AM until 7 PM, a National Day of Prayer FOR THE MUSLIM RELIGION was HELD on Capitol Hill, Beside the White House.",48
9552,Virginia House Speaker Bill Howell is allied to group pushing MIXED SEX BATHROOMS in Stafford Schools.,24
5921,"Congressional lawmakers earn their salaries FOR LIFE, which for House Minority Leader Nancy Pelosi would add up to $803,700 Dollars a year for LIFE including FREE medical.",22
7777,"""Obama Skips Out On Condemning Left-Wing Attacks On Gen. Petraeus Despite Casting Other 'Important Votes' Earlier And Later In The Day.""",22
8407,"Bob Menendez just voted to increase the governments debt ceiling to $1.9 TRILLION! In his 19 years in Congress, Menendez has helped overspend America over $15 TRILLION into debt.",22
1417,Former President Bill Clinton and his Clinton Health Access Initiative (CHAI) distributed watered-down HIV/AIDSdrugs to patients in sub-Saharan Africa.,21
5159,"What do Rutgers University, Kean University, Montclair State University, New Jersey City University, Stockton College, Rowan University and William Paterson all have in common? They all graduate less than 50 percent of their students within four years.",19
7453,"Ive been a cop in Lake County, Michigan, since 1982 thereabout. I conduct federal raids with the DEA and ATF and U.S. Marshals and the FBI and Texas Rangers.",19

In [49]:
train.nlargest(10, "punctuation_count")[
    ["statement", "punctuation_count"]
]

,statement,punctuation_count
4206,"""Let's pay attention to kids who are not going to college, which ends up being about 60 percent of the kids... and get them trained for the jobs that are there. Because, you know, there are auto mechanic jobs paying $50,000, $60,000 that they can't get filled. There are airline mechanic jobs paying a lot of money that can't get filled."" Remarks at AFSCME forum 6/19/2007",21
6904,"Sen. Clinton said ""the surge of troops in Iraq was 'working.' Now.... Sen. Clinton says the surge 'has failed' and that we should 'begin the immediate withdrawal of U.S. troops.'""",18
2213,"""Privatizing Social Security was a bad idea when George W. Bush proposed it. It's a bad idea today. Sen. McCain's campaign went even further ... suggesting ... to cut cost-of-living adjustments or to raise the retirement age.""",17
7292,"Portland Public Schools invites well-paid, well-fed school bureaucrats, administrators, teachers, other staff, non-needy students, affluent parents of students, and other adults, including on the other extreme the adult homeless, illegal aliens, fanatical Muslim terrorists, or drug addicted street people, to enjoy cheap breakfasts in taxpayer-paid school facilities amidst school children.",17
8146,"U.S. Rep. Jim Marshall (D-Ga.) refuses to return $37,000 in dirty campaign contributions from U.S. Rep. Charles Rangel (D-N.Y.)",17
9991,"Barbara Buono by the numbers: As a Trenton politician, she voted to raise taxes 154 times. Under her, property taxes up 70 percent. Backed a 16 percent sales tax increase. Utilities, nursing homes, cell phones, parking lots, lottery wins, gyms She taxed them all. Architect of Corzines budget, she drove New Jersey $2 billion into debt. Barbara Buono by the numbers: taking New Jersey backwards.",17
642,"""Hillary's baby bond proposal would give $5,000 to each of the 4-million babies born in the U.S. each year, totaling $20-billion per year, multiplied by four years = $80-billion.""",16
7284,"For [GM] to pay back everything it owes, it would have to sell its shares at $143 a share . . . where the highest value of a General Motors share ever was $43, $44, $46, whatever the dollars were . . .",16
8588,"US: Change in Income, 2009-13. Top 1%: +31.4%. Bottom 99%: +0.4%.",16
2379,"""Congressman John Lewis, an American hero, made allegations that Sarah Palin and I were somehow associated with ... the worst chapter in American history. ... And, Senator Obama, you didn't repudiate those remarks.""",15

In [50]:
print(train.shape)
print("Unique IDs:", train["id"].nunique())
print("Duplicate IDs:", train["id"].duplicated().sum())

(10269, 20)
Unique IDs: 10269
Duplicate IDs: 0

In [51]:
print("Train:", train.shape)
print("Valid:", valid.shape)
print("Test :", test.shape)

Train: (10269, 20)
Valid: (1284, 14)
Test : (1283, 14)

# Cross-Split Overlap

In [52]:
train_speaker_list = train["speaker"].unique()     
type(train_speaker_list)
len(train_speaker_list)

2916

In [53]:
common_train_test = []
common_train_valid = []
for speaker in train_speaker_list:
    if speaker in test["speaker"].values : 
        common_train_test.append(speaker)

    if speaker in valid["speaker"].values : 
        common_train_valid.append(speaker)

In [54]:
print(len(common_train_test))
print(len(common_train_valid))

449
446

In [55]:
for i in common_train_test:
    print(i)

scott-surovell
barack-obama
blog-posting
charlie-crist
robin-vos
robert-menendez
bernie-s
mitt-romney
doonesbury
george-will
national-republican-congressional-committee
dennis-richardson
eric-bolling
hillary-clinton
greater-wisconsin-political-fund
nancy-pelosi
rick-scott
tom-cotton
ted-cruz
kelly-ayotte
marco-rubio
rachel-maddow
chain-email
john-boehner
rick-perry
national-republican-senatorial-committee
ken-cuccinelli
donald-trump
john-mccain
michelle-obama
rudy-giuliani
john-depetro
terry-mcauliffe
republican-party-florida
jeanne-shaheen
karl-rove
bill-white
bob-goodlatte
cory-booker
joe-biden
florida-democratic-party
alison-lundergan-grimes
mitch-mcconnell
scott-walker
ron-johnson
donna-brazile
paul-ryan
adam-hasner
mark-pocan
kathleen-sebelius
dave-yost
alex-sink
sean-hannity
rush-limbaugh
patricia-morgan
dave-brat
mark-warner
rob-portman
john-cornyn
louie-gohmert
democratic-congressional-campaign-committee
armond-budish
kendrick-meek
americans-united-change
eric-cantor
ron-paul
gary-johnson
stephen-sweeney
sheldon-whitehouse
alan-grayson
chris-christie
americas-health-insurance-plans
greg-abbott
david-cicilline
wendy-davis
americans-tax-reform
tweets
hank-johnson
facebook-posts
lamar-smith
bill-johnson
eric-hovde
ben-carson
mark-neumann
sarah-palin
tom-niehaus
sherrod-brown
nextgen-climate
john-kasich
robby-mook
lindsey-graham
rand-paul
jeff-merkley
sheila-oliver
dick-cheney
michael-moore
bill-richardson
connie-mack
allen-west
steve-latourette
ted-strickland
us-chamber-commerce
julian-castro
michele-bachmann
dan-patrick
jeb-bush
florida-chamber-commerce
newt-gingrich
roy-blunt
andrew-napolitano
gerry-connolly
peter-kilmartin
david-dewhurst
associated-press
josh-mandel
nathan-deal
bill-clinton
mike-huckabee
bill-foster
rick-santorum
lloyd-doggett
rob-cornilles
dale-kooyenga
new-hampshire-democratic-party
mary-nolan
jim-steineke
steve-rothman
chuck-grassley
americans-prosperity
glenn-grothman
john-kerry
lou-greenwald
republican-governors-association
tom-price
carlos-curbelo
reince-priebus
victoria-taft
chris-abele
kenneth-block
american-crossroads
tim-kaine
debbie-wasserman-schultz
jimmy-carter
thomas-tobin
bobby-jindal
paul-krugman
mike-pence
kay-bailey-hutchison
democratic-national-committee
americans-job-security
rob-zerban
john-kitzhaber
katie-mcginty
ginny-brown-waite
naral-pro-choice
kasim-reed
richard-codey
alberta-darling
cory-gardner
priorities-usa-action
ed-gillespie
tommy-thompson
national-rifle-association
martin-omalley
jamie-radtke
kathleen-falk
sean-duffy
angel-taveras
bill-nelson
lincoln-chafee
kathleen-clyde
barbara-boxer
republican-national-committee-republican
randy-forbes
joaquin-castro
joe-manchin
carly-fiorina
betty-sutton
jim-renacci
committee-our-childrens-future
rush-holt
ed-fitzgerald
jack-kingston
todd-staples
barbara-buono
george-lemieux
viral-image
susana-martinez
roy-barnes
pat-mccrory
sharron-angle
patrick-murphy
fred-thompson
brian-kemp
leonidas-raptakis
ohio-democratic-party
national-right-life-committee
american-bridge-21st-century
pat-toomey
ward-armstrong
democratic-party-virginia
kamala-harris
john-oliver
ted-poe
jim-demint
john-lewis
gina-raimondo
herman-cain
glenn-beck
glenn-hegar
david-perdue
state-democratic-party-wisconsin
tim-pawlenty
jim-jordan
marsha-blackburn
sally-kohn
al-sharpton
jim-sensenbrenner
robin-wright
freedom-partners-action-fund
restore-our-future
jim-webb
tom-graves
russ-feingold
johnny-isakson
afscme
kirk-cox
sam-adams
bill-oreilly
new-jersey-democratic-state-committee
chris-matthews
maggie-hassan
john-edwards
one-wisconsin-now
harry-reid
george-allen
senate-majority-pac
laura-ingraham
glen-sturtevant
kurt-schrader
reid-ribble
doug-whitsett
lawrence-odonnell
dennis-kucinich
stephanie-cutter
david-brooks
nan-rich
donna-campbell
tammy-baldwin
boyd-richie
ed-schultz
jason-carter
jay-carney
elliott-naishtat
kris-jordan
bob-donovan
occupy-democrats
john-carlevale
thomas-perez
robert-hurt
don-beyer
robert-reich
brendan-doherty
jeff-stone
chris-dodd
ed-rendell
kevin-brady
crossroads-gps
mark-pryor
chris-larson
paul-sadler
heather-fiorentino
jim-kenney
pete-gallego
richard-saslaw
orrin-hatch
phil-gingrey
mary-burke
tom-tancredo
jay-nixon
michael-j-gardiner
nikki-haley
michael-mccaul
cliff-stearns
emma-watson
kinky-friedman
jeb-hensarling
nina-turner
american-action-network
donald-carcieri
american-future-fund
eileen-brady
chris-taylor
nicholas-kristof
jennifer-shilling
farouk-shami
jon-huntsman
joyce-beatty
don-balfour
hilary-rosen
edward-flynn
eric-greitens
debra-medina
scott-bruun
bob-buckhorn
steve-adler
tom-kean-jr
marilinda-garcia
lynn-westmoreland
ohio-republican-party
maciver-institute
service-employees-international-union-committee-po
cw-bill-young
leah-vukmir
steve-southerland
bruce-rauner
caroline-casagrande
no-casinos
rick-kriseman
blanche-lincoln
frank-wolf
libertarian-party-georgia
michael-bloomberg
lee-holloway
julie-lassa
sierra-club
silvestre-reyes
austin-scott
kirsten-gillibrand
mark-obenshain
michelle-nunn
christine-odonnell
votevetsorg
anthony-weiner
focus-family-action
leonard-lance
vernon-jones
wesley-clark
hank-gilbert
tom-leppert
gail-collins
van-jones
julie-pace
jeff-sessions
shawn-lindsay
jack-latvala
paul-manafort
scott-garrett
ted-ankrum
matt-mackowiak
dan-ramos
james-langevin
linda-finn
special-operations-opsec-education-fund
catherine-cortez-masto
citizens-transportation-mobility
mark-kirk
america-rising-now
bruce-starr
pam-bondi
john-ludlow
jennifer-granholm
centers-disease-control
alan-hays
allen-boyd
mike-collins
league-conservation-voters
matt-wand
red-white-and-blue-fund
john-burzichelli
dianne-feinstein
michael-chippendale
lenny-curry
donald-mceachin
don-lemon
gina-hinojosa
mahmoud-ahmadinejad
matt-gaetz
jan-schakowsky
steve-doocy
richard-durbin
katrina-shankland
texas-democratic-party
lois-frankel
jennifer-carroll
david-pennington
larry-pressler
sam-olens
bill-de-blasio
robert-gates
jay-rockefeller
chris-koster
rebecca-kleefisch
ending-spending-action-fund
bob-schieffer
charles-van-zant
scott-fitzgerald
kellyanne-conway
jeff-flake
new-jersey-sierra-club
rob-woodall
matt-lundy
arne-duncan
jonathan-stickland
jesse-ventura
dawson-hodgson
mayors-against-illegal-guns
rick-scotts-starbucks-heckler
jack-conway
mark-herring
steve-brown
ron-kind
linda-chavez-thompson
jim-doyle
bill-posey
john-boccieri
dean-cannon
matt-bevin
progressive-choice
gabrielle-giffords
hugh-hewitt
future-pac-oregon-house-democrats
brett-smiley
charles-boustany
john-oxendine
ovide-lamontagne
kathie-glass
jason-kander
john-albers
Yes-on-79
john-lee
william-obrien
american-federation-children
gerald-daugherty
steve-kagen
tim-mcginty
ameripac
morgan-griffith
brian-moran
jerome-corsi
bryan-fischer
jonathan-karl
bill-flores
rick-green
peter-orszag
tennessee-republican-party
david-plouffe
ezekiel-emanuel
christine-whitman

In [56]:
print("Unique train speakers:", len(train_speaker_list))
print("Unique test speakers:", len(test["speaker"].unique()))
print("Unique valid speakers:", len(valid["speaker"].unique()))

print(
    "Test speakers seen in train:",
    len(common_train_test) / len(test["speaker"].unique()) * 100
)

print(
    "Validation speakers seen in train:",
    len(common_train_valid) / len(valid["speaker"].unique()) * 100
)

Unique train speakers: 2916
Unique test speakers: 645
Unique valid speakers: 662
Test speakers seen in train: 69.61240310077518
Validation speakers seen in train: 67.37160120845923

In [57]:
train_statements = set(train["statement"])
test_statements = set(test["statement"])
valid_statements = set(valid["statement"])

common_train_test_statements = train_statements & test_statements
common_train_valid_statements = train_statements & valid_statements

print(
    "Statements shared with test:",
    len(common_train_test_statements)
)

print(
    "Statements shared with validation:",
    len(common_train_valid_statements)
)

Statements shared with test: 4
Statements shared with validation: 5

In [58]:
for stmt in common_train_test_statements:
    print("\nStatement:", stmt)
    print("Train labels:", train.loc[train["statement"] == stmt, "label"].unique())
    print("Test labels :", test.loc[test["statement"] == stmt, "label"].unique())

Statement: On a cap-and-trade plan.
Train labels: ['false']
Test labels : ['false']

Statement: On Common Core.
Train labels: ['false']
Test labels : ['false']

Statement: On offshore drilling.
Train labels: ['half-true']
Test labels : ['half-true']

Statement: Says Milken Institute rated San Antonio as nations top-performing local economy.
Train labels: ['true']
Test labels : ['true']

In [59]:
for stmt in common_train_valid_statements:
    print("\nStatement:", stmt)
    print("Train labels:", train.loc[train["statement"] == stmt, "label"].unique())
    print("Test labels :", valid.loc[valid["statement"] == stmt, "label"].unique())

Statement: Social Security is a Ponzi scheme.
Train labels: ['false']
Test labels : ['false']

Statement: On high-speed rail.
Train labels: ['false']
Test labels : ['false']

Statement: Martin Luther King Jr. was a Republican.
Train labels: ['false']
Test labels : ['false']

Statement: Americans havent had a raise in 15 years.
Train labels: ['mostly-true']
Test labels : ['mostly-true']

Statement: Signs letter saying Consumer Product Safety Commission is acting without consultation or input from the company to stop the sale of Buckyballs.
Train labels: ['false']
Test labels : ['false']

# Truth-History analysis

In [60]:
history_cols = [
    "barely_true_counts",
    "false_counts",
    "half_true_counts",
    "mostly_true_counts",
    "pants_on_fire_counts"
]

In [61]:
train[history_cols].isnull().sum()

barely_true_counts      0
false_counts            0
half_true_counts        0
mostly_true_counts      0
pants_on_fire_counts    0
dtype: int64

In [62]:
train[history_cols].describe()

,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts
count,10269.000000,10269.000000,10269.000000,10269.000000,10269.000000
mean,11.560132,13.313857,17.195637,16.490505,6.202746
std,19.006447,24.140583,35.948211,36.251253,16.117701
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,2.000000,3.000000,3.000000,1.000000
75%,12.000000,15.000000,13.000000,11.000000,5.000000
max,70.000000,114.000000,160.000000,163.000000,105.000000

In [63]:
for col in history_cols:
    print(col, (train[col] == 0).sum())

barely_true_counts 3033
false_counts 2818
half_true_counts 2610
mostly_true_counts 2761
pants_on_fire_counts 4779

In [64]:
(train[history_cols] < 0).sum()

barely_true_counts      0
false_counts            0
half_true_counts        0
mostly_true_counts      0
pants_on_fire_counts    0
dtype: int64

In [67]:
train["total_history"] = train[history_cols].sum(axis=1)

train["total_history"].describe()

count    10269.000000
mean        64.762879
std        115.993255
min          0.000000
25%          2.000000
50%         11.000000
75%         65.000000
max        473.000000
Name: total_history, dtype: float64

In [79]:
train.nlargest(493, "total_history")[
    ["speaker"] + history_cols + ["total_history"]
]

,speaker,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts,total_history
2,barack-obama,70,71,160,163,9,473
7,barack-obama,70,71,160,163,9,473
16,barack-obama,70,71,160,163,9,473
74,barack-obama,70,71,160,163,9,473
105,barack-obama,70,71,160,163,9,473
...,...,...,...,...,...,...,...
10166,barack-obama,70,71,160,163,9,473
10187,barack-obama,70,71,160,163,9,473
10210,barack-obama,70,71,160,163,9,473
10221,barack-obama,70,71,160,163,9,473
10249,barack-obama,70,71,160,163,9,473

In [78]:
(train["total_history"] == 473).value_counts()

total_history
False    9776
True      493
Name: count, dtype: int64

In [80]:
train.loc[
    train["total_history"] == train["total_history"].max(),
    "speaker"
].value_counts()

speaker
barack-obama    493
Name: count, dtype: int64

In [81]:
speaker_history_variation = (
    train.groupby("speaker")[history_cols]
    .nunique()
)

speaker_history_variation.max()

barely_true_counts      2
false_counts            2
half_true_counts        2
mostly_true_counts      2
pants_on_fire_counts    2
dtype: int64

In [82]:
varying_speakers = speaker_history_variation[
    (speaker_history_variation > 1).any(axis=1)
]

varying_speakers

,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts
speaker,,,,,
danny-tarkanian,2,1,2,2,1
kasim-reed,2,1,2,2,2
robert-puente,1,2,2,1,1

In [83]:
speaker = varying_speakers.index[0]

train.loc[
    train["speaker"] == speaker,
    ["speaker"] + history_cols
].drop_duplicates()

,speaker,barely_true_counts,false_counts,half_true_counts,mostly_true_counts,pants_on_fire_counts
3150,danny-tarkanian,0,0,0,1,0
3774,danny-tarkanian,1,0,1,0,0

# metadata cardinality/frequency

In [84]:
metadata_cols = [
    "subject",
    "speaker",
    "speaker_job_title",
    "state_info",
    "party_affiliation",
    "context"
]

for col in metadata_cols:
    print(f"\n{col}")
    print("Unique values:", train[col].nunique())
    print(train[col].value_counts(dropna=False).head(10))

subject
Unique values: 3836
subject
health-care             382
taxes                   308
immigration             253
elections               253
education               238
candidates-biography    190
economy                 138
guns                    130
economy,jobs            125
federal-budget          122
Name: count, dtype: int64

speaker
Unique values: 2916
speaker
barack-obama       493
donald-trump       274
hillary-clinton    239
mitt-romney        180
scott-walker       150
john-mccain        148
rick-perry         142
chain-email        142
marco-rubio        117
rick-scott         115
Name: count, dtype: int64

speaker_job_title
Unique values: 1186
speaker_job_title
NaN                           2902
President                      497
U.S. Senator                   480
Governor                       391
President-Elect                274
U.S. senator                   263
Presidential candidate         254
Former governor                180
U.S. Representative            172
Milwaukee County Executive     150
Name: count, dtype: int64

state_info
Unique values: 83
state_info
NaN             2211
Texas           1009
Florida         1001
Wisconsin        716
New York         658
Illinois         562
Ohio             448
Georgia          427
Virginia         409
Rhode Island     371
Name: count, dtype: int64

party_affiliation
Unique values: 23
party_affiliation
republican      4510
democrat        3345
none            1746
organization     220
independent      149
newsmaker         58
activist          40
libertarian       40
journalist        38
columnist         36
Name: count, dtype: int64

context
Unique values: 4360
context
a news release       242
an interview         229
a press release      223
a speech             216
a TV ad              180
a tweet              156
a campaign ad        132
a television ad      124
a radio interview    107
NaN                  100
Name: count, dtype: int64